import { cookies } from "next/headers"

/**
 * @param token - session token generated by the generateSessionToken function
 * @param expiresAt - the date when the session token expires
 */
export async function setSessionTokenCookie(token: string, expiresAt: Date) {
    ;(await cookies()).set("session", token, {
        httpOnly: true,
        sameSite: "lax",
        secure: process.env.NODE_ENV === "production",
        expires: expiresAt,
        path: "/",
    })
}

export async function deleteSessionTokenCookie() {
    ;(await cookies()).set("session", "", {
        httpOnly: true,
        sameSite: "lax",
        secure: process.env.NODE_ENV === "production",
        maxAge: 0,
        path: "/",
    })
}
